### ISSUE TITLE
Unable to build glut on RHEL 6

### ISSUE THREAD

**Issue by greevex** [Ponup/phpopengl#6]
freeglut-devel info:
Name        : freeglut-devel
Arch        : x86_64
Version     : 2.6.0
Release     : 1.el6
Size        : 109 k
Repo        : installed
From repo   : sl
Summary     : Freeglut developmental libraries and header files
URL         : http://freeglut.sourceforge.net
License     : MIT
Description : Developmental libraries and header files required for developing or compiling
            : software which links to the freeglut library, which is an open source
            : alternative to the popular GLUT library, with an OSI approved free software
            : license.

Build process: http://ascii.io/a/11736

**Comment by santiagolizardo** [comment]
Glut is no longer part of this extension. All the Glut related code has been removed.
In order to create a window, GL context and capture events you would need an additional PHP extension: SDL.
This example shows how to use PHP-SDL and PHP-OpenGL together.
